
auth.token=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

defaults.org=madebysteven
defaults.project=guidr-mobile

defaults.url=https://sentry.io/
