name: CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/jobs/job-lint.yml

  test:
    uses: ./.github/workflows/jobs/job-test.yml

  typecheck:
    uses: ./.github/workflows/jobs/job-typecheck.yml

  android-build:
    uses: ./.github/workflows/jobs/job-android-build.yml

  ios-build:
    uses: ./.github/workflows/jobs/job-ios-build.yml
